### PR TITLE
Setting to disable indicator icon if disconnected from VPN

### PR DESCRIPTION
**Pull request by rubiojr**
Adds a new setting to disable the indicator icon when not connected to the VPN.

This makes it a bit easier for me to realize that the VPN is disabled, instead of using a greyed out icon which is, perhaps, a bit harder to distinguish from the connected icon for the untrained eyes.

Doesn't change defaults, so the disconnected icon is still show by default if the show-icon is enabled.

Another option would be to make this behavior default and avoid the extra setting. A personal preference I guess.

### CODE REVIEW

**Comment by Pobega** [comment]
This LGTM but I'm away for a few days for the US Holiday, will test and merge as soon as I'm back at my desktop.

I think switching this behavior to default actually makes sense, it'd be more in line with the WiFi/Ethernet/BT indicators.

**Comment by Pobega** [comment]
I just tested this and it doesn't seem to work on my machine, I'm not exactly sure why. Does it work for you?

**Comment by Pobega** [comment]
I think it might be being overridden by the `Display indicator icon` setting, which is forcing the icon to `visible` even though your code is trying to hide it.

**Review by Pobega — CHANGES_REQUESTED** [review]
I think it might be being overridden by the Display indicator icon setting, which is forcing the icon to visible even though your code is trying to hide it.

The issue is that the way that setting is implemented it directly has access to toggling _indicator.visible based on the user config. It might take a bit of rewriting to get the two different preferences to control the same setting. It might be better to bind them both to a function that checks what it should do based on the other setting.

**Comment by rubiojr** [comment]
Thanks for the 👀, I'll have a closer look. It's working here, but Im a javascript n00b, so it's certainly possible I missed something.

**Comment by Pobega** [comment]
Closed by https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/pull/35

**Pull request closed without merging**
