### PR TITLE
Add option to only show indicator icon when vpn is connected

### PR DESCRIPTION
**Pull request by davidscholberg**
This commit adds an option to only show the indicator icon in the system tray when the VPN is connected. This commit builds off of the work done by @rubiojr in https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/pull/33 and makes the changes suggested by @Pobega in that PR.

Specifically, the following changes are made in this PR:

* Add a toggle in the app settings to only show the tray icon when the vpn is connected, and make this setting's sensitivity linked to the "show icon" setting (such that this new option is greyed out if "show icon" is false).
* Remove the direct binding between the "show icon" setting and the visibility of the tray icon.
* Add the new setting to the list of settings that call _sync when changed.
* Add a function that determines what the visibility of the tray icon should be based on the two user settings and the connection state, and set the visibility of the tray icon in the _sync function.

### CODE REVIEW

**Comment by davidscholberg** [comment]
Forgot to mention that this new setting is set to "true" by default, which is in line with the change suggested in this comment: https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/pull/33#issuecomment-1824521795

**Review by Pobega — COMMENTED** [review]
This LGTM at first glance. Give me an opportunity to try it out on my machine after work and I'll merge & submit to ego.

**Comment by Pobega** [comment]
Thanks for doing the work on this! Appreciate it.

**Comment by davidscholberg** [comment]
Thank you for the quick merge and for a great extension!

And thank you to @rubiojr for the initial idea and effort.

**Comment by rubiojr** [comment]
@davidscholberg beat me to the punch. Thanks for taking care of it!

**Pull request merged**
